apiVersion: v1
kind: Namespace
metadata:
  name: debug
---
apiVersion: v1
kind: Pod
metadata:
  name: debug-pod-01
  namespace: debug
  labels:
    app: swiss-army-knife
spec:
  containers:
  - name: debug-pod-01
    image: leodotcloud/swiss-army-knife:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: debug-pod-01-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: debug-pod-01-pvc
  namespace: debug
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: debug-pod-02
#   namespace: debug
#   labels:
#     app: swiss-army-knife
# spec:
#   containers:
#   - name: debug-pod-02
#     image: leodotcloud/swiss-army-knife:latest
#     command: ["/bin/sleep", "3650d"]
#     imagePullPolicy: IfNotPresent
#   restartPolicy: Always
#   nodeSelector:
#     kubernetes.io/hostname: worker-63ce50cfca582
